title: NeuroGEARS
description: Neuroscience, Games, Interaction, Robotics
google_analytics:
theme: jekyll-theme-cayman

twitter_username: neurogears
github_username:  neurogears
email: contact@neurogears.org
copyright: © 2017 NeuroGEARS Ltd.

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock