title: NeuroGEARS
description: Neuroscience, Games, Interaction, Robotics
google_analytics: UA-106624760-1
theme: jekyll-theme-cayman

twitter_username: neurogears
github_username:  neurogears
email: contact@neurogears.org
copyright: © 2017 NeuroGEARS Ltd.

collections:
  pages:
    output: true
exclude:
  - Gemfile
  - Gemfile.lock